Add option to use partytown for GTM
rapidez/gtm pull request #3
Opened 2023-04-19 09:28 UTC by indykoning

2023-07-27 12:47 UTC, indykoning commented on resources/views/partytown/config.blade.php
> +            if (@json(config('rapidez.partytown')).includes(url.host)) {
```suggestion
            if (@json(config('rapidez.partytown.domain_whitelist')).includes(url.host)) {
```

2023-08-23 12:08 UTC, royduin requested changes

2023-08-23 12:19 UTC, indykoning commented on src/GTMServiceProvider.php
> +            ->middleware('web')
I have it in there to keep with the expectation that a web.php has the web middleware, but it is not needed for this proxy route.

Is it better to move the proxy route to the serviceprovider without web middleware, or just remove the web middleware here?

2023-08-23 14:23 UTC, indykoning commented
I have found a call done via a POST request which we do not proxy, i will test and update the code for that

2023-08-24 07:10 UTC, merged